// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hmsv3/app/navigation/app_router.dart';
import 'package:hmsv3/firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:hmsv3/app/config/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    const ProviderScope( // For Riverpod
      child: MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final goRouter = ref.watch(goRouterProvider);

    return MaterialApp.router(
      title: 'Healthy!', // From your mockups
      theme: AppTheme.lightTheme, // Use the theme
      darkTheme: AppTheme.darkTheme, // Optional: if you want a dark theme
      themeMode: ThemeMode.light, // Or ThemeMode.system, ThemeMode.dark
      routerConfig: goRouter,
      debugShowCheckedModeBanner: false,
    );
  }
}